#Auto-generated by the projectmake utility
BUILD_DIR = .build

.PHONY: all ship purge clean mirror

MIRROR_FLAGS ?= -vf
 
ifeq ($(OS),Windows_NT)
  EXTRA_BUILD_FLAGS :=
else
  EXTRA_BUILD_FLAGS := -- --no-print-directory
endif
all:
	@$(MAKE) mirror MIRROR_FLAGS=-fq
	@if [ ! -d "$(BUILD_DIR)" ]; then \
		mkdir -p $(BUILD_DIR); \
		cmake -S . -B $(BUILD_DIR) -DFORCE_JSL_CLONE=OFF; \
	fi
	@cmake --build $(BUILD_DIR) --target fade $(EXTRA_BUILD_FLAGS) 

mirror:
	@command -v lsj>/dev/null 2>&1 && lsj lib/include/FADE/ModelSettings.h lib/include/FADE/*/*Settings.h app/Settings.h $(mirror_flags) || echo "no mirror found, using cached values" 
ship:
	@make mirror
	@mkdir -p $(BUILD_DIR)
	@cmake -S . -B $(BUILD_DIR) -DFORCE_JSL_CLONE=ON
	@cmake --build $(BUILD_DIR) --target fade -- --no-print-directory

# 3. Clean up only the build artifacts
purge:
	@echo "Removing all build files"
	@rm -rf $(BUILD_DIR)
	@rm -f fade

clean:
	@echo "Rebuilding from scratch"
	@make purge
	@make all 
