#Auto-generated by the projectmake utility
BUILD_DIR = .build

.PHONY: all ship purge clean mirror

MIRROR_FLAGS ?= -vf
MAKEFLAGS += --no-print-directory
 
all:
	@$(MAKE) mirror MIRROR_FLAGS=-fq
	@if [ ! -d "$(BUILD_DIR)" ]; then \
		mkdir -p $(BUILD_DIR); \
		cmake -S . -B $(BUILD_DIR) -DFORCE_JSL_CLONE=OFF; \
	fi
	@cmake --build $(BUILD_DIR) --target fade -- --no-print-directory

mirror:
	@command -v lsj>/dev/null 2>&1 && lsj FADE/include/FADE/ModelSettings.h FADE/include/FADE/*/*Settings.h app/Settings.h $(MIRROR_FLAGS) || echo "No mirror found, using cached values" 
ship:
	@make mirror
	@mkdir -p $(BUILD_DIR)
	@cmake -S . -B $(BUILD_DIR) -DFORCE_JSL_CLONE=ON
	@cmake --build $(BUILD_DIR) --target fade -- --no-print-directory

# 3. Clean up only the build artifacts
purge:
	@echo "Removing all build files"
	@rm -rf $(BUILD_DIR)
	@rm -f fade

clean:
	@echo "Rebuilding from scratch"
	@make purge
	@make all --no-print-directory
