#Auto-generated by the projectmake utility
BUILD_DIR = .build

.PHONY: all ship purge clean mirror

# 1. The default target: ensures .build exists, runs cmake, then builds


all:
	@make mirror
	@mkdir -p $(BUILD_DIR)
	@cmake -S . -B $(BUILD_DIR) -DFORCE_JSL_CLONE=OFF
	@cmake --build $(BUILD_DIR) --target fade -- --no-print-directory

mirror:
	@command -v lsj>/dev/null 2>&1 && lsj FADE/include/FADE/ModelSettings.h FADE/include/FADE/*/*Settings.h app/Settings.h -fv || echo "No mirror found, using cached values" 
ship:
	@make mirror
	@mkdir -p $(BUILD_DIR)
	@cmake -S . -B $(BUILD_DIR) -DFORCE_JSL_CLONE=ON
	@cmake --build $(BUILD_DIR) --target fade -- --no-print-directory

# 3. Clean up only the build artifacts
purge:
	@echo "Removing all build files"
	@rm -rf $(BUILD_DIR)
	@rm -f fade

clean:
	@echo "Rebuilding from scratch"
	@make purge
	@make all --no-print-directory
